services:
  - type: web
    name: beat-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT beat_api:app
    plan: free
    envVars:
      - key: PORT
        value: 5000